name: ui_paste_component
description: "UI paste component"
version: 0.0.2
homepage: https://github.com/ShahzodAtabayev/ui_paste_component

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shahzod.ui_paste_component
        pluginClass: UiPasteComponentPlugin
      ios:
        pluginClass: UiPasteComponentPlugin

