name: ui_paste_component
version: 0.0.5
description: "UI paste component"
homepage: https://github.com/ShahzodAtabayev/ui_paste_component

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shahzod.ui_paste_component
        pluginClass: UiPasteComponentPlugin
      ios:
        pluginClass: UiPasteComponentPlugin

